title: "NUSConnect"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2425S2-CS2103T-T16-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
